#!/usr/bin/env python3
"""
Modal Training Script for Cipher ML

This script loads training data generated by train-cipher-model.ts
and triggers the Modal training function.

Usage:
    python scripts/modal-train.py [--data-file=path] [--version=v1.0.0]
"""

import argparse
import json
import os
import sys
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Train Cipher ML model on Modal")
    parser.add_argument(
        "--data-file",
        type=str,
        help="Path to training data JSON file",
    )
    parser.add_argument(
        "--version",
        type=str,
        default=None,
        help="Model version (default: from data file or auto-generated)",
    )
    args = parser.parse_args()

    # Find data file
    data_file = args.data_file
    if not data_file:
        # Look for latest training data file
        data_dir = Path(".cipher-training")
        if data_dir.exists():
            files = sorted(data_dir.glob("training-data-*.json"), reverse=True)
            if files:
                data_file = str(files[0])

    if not data_file or not os.path.exists(data_file):
        print("❌ No training data file found!")
        print("   Run: npx tsx scripts/train-cipher-model.ts")
        print("   Or specify: --data-file=path/to/data.json")
        sys.exit(1)

    print(f"📂 Loading training data from: {data_file}")

    with open(data_file) as f:
        data = json.load(f)

    X = data["X"]
    y = data["y"]
    model_version = args.version or data.get("model_version", f"v{int(__import__('time').time())}")
    metadata = data.get("metadata", {})

    print(f"   Samples: {len(X):,}")
    print(f"   Features: {len(X[0]) if X else 0}")
    print(f"   Model version: {model_version}")

    # Import Modal and invoke training
    try:
        import modal
    except ImportError:
        print("❌ Modal not installed. Run: pip install modal")
        sys.exit(1)

    print("\n🚀 Starting Modal training...")
    print("   This may take several minutes for large datasets.\n")

    # Import the training function
    from modal import Function

    # Look up the deployed function
    try:
        train_fn = Function.from_name("cipher-ml", "train_model")
    except modal.exception.NotFoundError:
        print("❌ Cipher ML app not deployed!")
        print("   Run: modal deploy modal/cipher-ml.py")
        sys.exit(1)

    # Call the training function
    result = train_fn.remote(
        X=X,
        y=y,
        model_version=model_version,
        metadata=metadata,
    )

    if result.get("success"):
        print("\n✅ Training complete!")
        print(f"   Model version: {result['model_version']}")
        print(f"   Model path: {result['model_path']}")
        print(f"\n📊 Metrics:")
        metrics = result["metrics"]
        print(f"   Precision: {metrics['precision']*100:.2f}%")
        print(f"   Recall: {metrics['recall']*100:.2f}%")
        print(f"   F1 Score: {metrics['f1']*100:.2f}%")
        print(f"   AUC-ROC: {metrics['auc_roc']*100:.2f}%")

        print(f"\n🎯 Top Features:")
        for feat in result.get("top_features", [])[:10]:
            print(f"   {feat['display_name']}: {feat['importance']*100:.2f}%")

        # Save results
        results_file = data_file.replace(".json", "-results.json")
        with open(results_file, "w") as f:
            json.dump(result, f, indent=2)
        print(f"\n📁 Results saved to: {results_file}")
    else:
        print(f"\n❌ Training failed: {result.get('error', 'Unknown error')}")
        sys.exit(1)

    print("\n✨ Done!")


if __name__ == "__main__":
    main()
